---
        
- rule:
    paths:
      - "specification/@(applicationinsights|operationalinsights)/**"
    reviewers:
      - akning-ms
      - JeffreyRichter
      - markweitzel
      
- rule:
    paths:
      - "specification/authorization/**"
    reviewers:
      - ruowan
      - markweitzel
      
- rule:
    paths: "specification/common-types/**"
    reviewers:
      - raych1
      - akning-ms
      - leni-msft
      - ruowan
      - jianyexi
      - zhenglaizhang
      
- rule:
    paths: "specification/compute/**"
    reviewers:
      - ArcturusZhang
      - weidongxu-microsoft
      - mikekistler
      
- rule:
    paths:
      - "specification/confidentialledger/data-plane/**"
    reviewers:
      - christothes
      - JeffreyRichter
      - markweitzel

- rule:
    paths:
      - "specification/containerregistry/**"
    reviewers:
      - fengzhou-msft
      - mikekistler
      - markweitzel
      
- rule:
    paths:
      - "specification/datafactory/**"
    reviewers:
      - leni-msft
       - mikekistler
       - markweitzel
       
- rule:
    paths:
      - "documentation/**"
    reviewers:
      - josefree
      - akning-ms
      - JeffreyRichter
      - markweitzel

- rule:
    # eventgrid data-plane PR
    paths:
      - "specification/eventgrid/data-plane/**"
    reviewers:
      - lmazuel
      - mikekistler
      - weidongxu-microsoft
     
- rule:
    paths: "specification/eventhub/**"
    reviewers:
      - ruowan
      - markweitzel
      - johanste
      
- rule:
    # data-plane PR
    paths:
      - "specification/**/data-plane/iot**"
    reviewers:
      - drwill-ms
      - JeffreyRichter
      - rysweet
      
- rule:
    paths:
      - "specification/keyvault/**"
    reviewers:
      - zhenglaizhang
      - markweitzel
      - JeffreyRichter
      
- rule:
    paths:
      - "specification/machinelearningservices/**"
    reviewers:
      - ArcturusZhang
      - markweitzel

- rule:	
    paths: "specification/mediaservices/**"	
    reviewers:	
      - allenjzhang
      - JeffreyRichter
      - johanste
      
- rule:
    paths:
      - "specification/mixedreality/**"
      - "specification/hdinsight/**"
    reviewers:
      - leni-msft
      - JeffreyRichter
      - rysweet

- rule:
    paths:
      - "specification/network/**"
    reviewers:
      - lirenhe
      - raych1
      - mikekistler
      - weidongxu-microsoft
      
- rule:
    paths: "specification/@(resources|powerplatform|appplatform|deviceupdate|servicelinker)/**"
    reviewers:
      - raych1
      - JeffreyRichter
      - markweitzel
      
- rule:
    paths: "specification/@(security|edgeorder|synapse)/**"
    reviewers:
      - ruowan
      - mikekistler
      - weidongxu-microsoft
     
      
- rule:
    paths: "specification/signalr/**"
    reviewers:
      - leni-msft
      - JeffreyRichter
      - johanste
      
- rule:
    paths: "specification/sql/**"
    reviewers:
      - zhenglaizhang      

      
- rule:
    paths:
      - "specification/storage/**"
    reviewers:
      - jianyexi
      - tg-msft
      - johanste
      
- rule:
    # synapse data-plane PR
    paths:
      - "specification/synapse/data-plane/**"
    reviewers:
      - lmazuel
      - mikekistler
      - weidongxu-microsoft
      
- rule:
    # translator data-plane PR
    paths:
      - "specification/cognitiveservices/data-plane/TranslatorText/**"
    reviewers:
      - kristapratico
      - maririos
      - johanste
      - markweitzel
      
- rule:
    paths:
      - "specification/web/**"
    reviewers:
      - weidongxu-microsoft
      
- rule:
    # data-plane PR
    paths:
      - "specification/**/data-plane/**"
    reviewers:
      - markweitzel
      - mikekistler
      - weidongxu-microsoft
      - haocornell-ms
      - blackrider97
      - MushMal
                   
- rule:
    paths:
      - "**/package.json"	
      - ".github/**"	
      - "**/azure-pipelines.yml"	
      - ".azure-pipelines/**"	
      - ".azure-pipelines-preproduction/**"	
    reviewers:
      - akning-ms
      - raych1
      - zhenglaizhang

- rule:
    # manager-plane PR
    paths:
      - "**"
    reviewers:
      - lirenhe
      - weidongxu-microsoft
      - ArcturusZhang
      - raych1
      - akning-ms
      - leni-msft
      - ruowan
      - jianyexi
      - zhenglaizhang
      - chunyu3
      - changlong-liu
      - msyyc
      - qiaozha
      - weidong
