name: Greetings

on:
  pull_request:
    paths:
      - 'specification/compute/**'

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Prettify code
      uses: creyD/prettier_action@v2.2
